// The people and jobs the prototype runs on, so usability testers see a full app and not three
// cards. Flipkart and Abhinav are the V6 screens' own data; the rest follow the same shapes.

/* ── jobs the candidate can ask about ─────────────────────────────────────── */
export type Job = {
  id: string;
  title: string;
  company: string;
  /** the logo file on white tiles (lists, requests) */
  logo: string;
  /**
   * The big panel at the top of Job details: the company's brand colour, with its logo in
   * white on it. `mark` keeps a logo's own colours (Blinkit on its yellow, Microsoft's squares).
   */
  banner: { bg: string; src?: string; w: number; h: number; keep?: boolean; word?: string; wordColor?: string };
  city: string;
  cityShort: string;
  pay: string;
  years: string;
  jobId: string;
  referrer: { name: string; role: string };
  when: string;
  /** the job's seven skills, and which of them Abhinav's resume doesn't show */
  skills: string[];
  missing: string[];
  /** a referrer who is full this week can't take a request */
  full?: boolean;
  common?: { logo?: string; text: string };
  work: string[];
  about: string;
  looking: string[];
  resp: string[];
  tips: string[];
  employer: string;
};

export const DESIGN = ["UX research", "Interaction design", "Prototyping", "AI-assisted design", "Design system", "Figma"];

export const JOBS: Job[] = [
  {
    id: "flipkart",
    title: "Interaction Designer",
    company: "Flipkart",
    logo: "flipkart",
    banner: { bg: "#2874F0", src: "/images/sidedoor/flipkart-white.svg", w: 242, h: 64, keep: true },
    city: "Bengaluru, KA",
    cityShort: "Bengaluru",
    pay: "₹28–40 LPA",
    years: "3+ years",
    jobId: "184223",
    referrer: { name: "Nithin Agarwal", role: "Design Manager, Flipkart" },
    when: "Thursday",
    skills: ["Interaction design", "Figma", "User research", "Prototyping", "AI-assisted design", "Design system", "A/B testing"],
    missing: ["AI-assisted design", "Design system", "A/B testing"],
    common: { logo: "makemytrip", text: "Both worked at MakeMyTrip" },
    work: ["Remote or hybrid", "Joining within 30 days"],
    about:
      "Design and deliver intuitive checkout and post-purchase experiences used by millions of users. Work closely with product and engineering to simplify complex flows and improve conversion, trust, and usability. Contribute across the full design lifecycle, from interaction modeling to high-fidelity execution and validation.",
    looking: [
      "3+ years of experience designing web or mobile products",
      "Strong skills in interaction design, user flows, and usability",
      "Experience creating wireframes, prototypes, and high-fidelity UI",
      "Ability to collaborate closely with product and engineering teams",
    ],
    resp: [
      "Own and design high-impact checkout and payment experiences",
      "Collaborate closely with product and engineering to solve complex user problems",
      "Create wireframes, interactive prototypes, and polished high-fidelity designs",
      "Lead and apply user research insights to continuously improve key flows",
    ],
    tips: [
      "Present a portfolio showcasing your strongest interaction design work, primarily created in Figma",
      "Clearly articulate your end-to-end design process, from research and exploration to wireframes and prototypes",
      "Demonstrate measurable impact through metrics such as conversion, engagement, or scale",
      "Showcase strong collaboration with product managers and engineers across projects",
    ],
    employer:
      "Flipkart is one of India’s leading e-commerce platforms, serving millions of customers across categories. The company focuses on building scalable, customer-first experiences through technology, design, and innovation.",
  },
  {
    id: "phonepe",
    title: "Sr. Product Designer",
    company: "PhonePe",
    logo: "phonepe",
    banner: { bg: "#5F259F", src: "/images/sidedoor/phonepe.svg", w: 200, h: 62 },
    city: "Pune, MH",
    cityShort: "Pune",
    pay: "₹40–50 LPA",
    years: "5+ years",
    jobId: "PP-2291",
    referrer: { name: "Avinash Banerjee", role: "Design Lead, PhonePe" },
    when: "Wednesday",
    skills: ["Interaction design", "Figma", "Payments UX", "Design system", "User research", "Motion design", "Prototyping"],
    missing: ["Payments UX", "Design system", "Motion design"],
    full: true,
    work: ["On-site", "Joining within 60 days"],
    about:
      "Lead design for PhonePe’s merchant payments, used by 40 million shops across India. Turn messy offline journeys into flows a first-time smartphone user can finish.",
    looking: [
      "5+ years designing consumer or fintech products",
      "A portfolio with shipped work at scale",
      "Comfort designing for low-literacy and vernacular users",
      "Experience mentoring other designers",
    ],
    resp: [
      "Own the merchant onboarding and settlement journeys",
      "Run field research with shop owners in tier 2 and 3 cities",
      "Shape the design system’s payment components",
      "Partner with product on quarterly roadmaps",
    ],
    tips: ["Show one flow you simplified end to end", "Bring numbers: completion, errors, time taken", "Talk about designing for trust with money"],
    employer: "PhonePe is India’s largest UPI app, with over 500 million registered users and payments in every pin code.",
  },
  {
    id: "google",
    title: "UX Designer, Google Pay",
    company: "Google",
    logo: "google",
    // the real four-colour wordmark on white, its own ground; turned white on blue it stopped reading as Google (Devansh, 24 Sep)
    banner: { bg: "#FFFFFF", src: "/images/sidedoor/google.svg", w: 190, h: 64, keep: true },
    city: "Bengaluru, KA",
    cityShort: "Bengaluru",
    pay: "₹45–60 LPA",
    years: "4+ years",
    jobId: "G-5820",
    referrer: { name: "Ishita Nair", role: "Senior UX Designer, Google" },
    when: "Wednesday",
    skills: ["Interaction design", "User research", "Prototyping", "Figma", "Accessibility", "Design system", "Usability testing"],
    missing: ["Accessibility", "Design system"],
    common: { text: "Both studied at NID" },
    work: ["Hybrid", "Joining within 60 days"],
    about:
      "Design how the next 200 million Indians pay, save and borrow with Google Pay. Work across research, interaction and visual design with a small, senior team.",
    looking: [
      "4+ years of UX design for mobile products",
      "Strong craft in interaction and visual design",
      "Experience running and synthesising user research",
      "Clear writing about design decisions",
    ],
    resp: [
      "Design end-to-end flows for payments and credit",
      "Prototype and test ideas with users every sprint",
      "Work with Material Design on shared components",
      "Present work to product and engineering leads",
    ],
    tips: ["Keep case studies short: problem, choice, result", "Show research that changed your design", "Mention accessibility work if you have it"],
    employer: "Google builds products used by billions. Google Pay in India handles a large share of the country’s UPI payments.",
  },
  {
    id: "sarvam",
    title: "Founding Product Designer",
    company: "Sarvam AI",
    logo: "sarvam",
    banner: { bg: "linear-gradient(120deg, #1D4ED8 0%, #6D5BD0 45%, #F97316 100%)", src: "/images/sidedoor/sarvam-white.svg", w: 220, h: 35, keep: true },
    city: "Bengaluru, KA",
    cityShort: "Bengaluru",
    pay: "₹40–60 LPA",
    years: "3+ years",
    jobId: "SRV-014",
    referrer: { name: "Arjun Menon", role: "Design Lead, Sarvam AI" },
    when: "Tuesday",
    skills: ["Interaction design", "AI-assisted design", "Prototyping", "Figma", "Product strategy", "Voice UX", "User research"],
    missing: ["AI-assisted design", "Voice UX"],
    work: ["On-site", "Joining within 30 days"],
    about:
      "Design the first products built on Sarvam’s Indian-language models: voice agents, translation and assistants that work in 10 Indian languages.",
    looking: [
      "3+ years designing products from zero to one",
      "Curiosity about AI, voice and language",
      "Comfort shipping fast and changing your mind",
      "Strong prototyping skills",
    ],
    resp: [
      "Own design for a new voice assistant product",
      "Prototype model behaviour with researchers",
      "Set up the first design system",
      "Talk to users in Hindi, Tamil and Kannada",
    ],
    tips: ["Show something you built with AI tools", "Early-stage experience counts more than big names", "Tell us which Indian languages you speak"],
    employer: "Sarvam AI builds full-stack AI for India, from foundation models to apps that work in Indian languages.",
  },
  {
    id: "meta",
    title: "Product Designer, WhatsApp",
    company: "Meta",
    logo: "meta",
    banner: { bg: "#0081FB", src: "/images/sidedoor/meta.svg", w: 230, h: 47 },
    city: "Gurugram, HR",
    cityShort: "Gurugram",
    pay: "₹55–75 LPA",
    years: "5+ years",
    jobId: "MT-9034",
    referrer: { name: "Siddharth Rao", role: "Product Design Manager, Meta" },
    when: "Tuesday",
    skills: ["Interaction design", "Product strategy", "Prototyping", "Figma", "Data-informed design", "User research", "Systems thinking"],
    missing: ["Data-informed design"],
    work: ["Hybrid", "Joining within 90 days"],
    about:
      "Design WhatsApp Business tools for India’s small businesses: catalogues, payments and customer chats for millions of shops.",
    looking: [
      "5+ years of product design experience",
      "A track record of shipping at scale",
      "Comfort with metrics and experiments",
      "Strong product thinking",
    ],
    resp: [
      "Own the design of business messaging features",
      "Define problems with product and data science",
      "Run experiments and read the results",
      "Raise the design bar across the team",
    ],
    tips: ["Lead with product thinking, not visuals", "Show how you used data in a decision", "Pick two strong projects over five average ones"],
    employer: "Meta builds WhatsApp, Instagram and Facebook. India is WhatsApp’s largest market.",
  },
  {
    id: "blinkit",
    title: "Senior Product Designer",
    company: "Blinkit",
    logo: "blinkit",
    banner: { bg: "#F8CB46", src: "/images/sidedoor/blinkit.svg", w: 110, h: 110, keep: true },
    city: "Gurugram, HR",
    cityShort: "Gurugram",
    pay: "₹35–45 LPA",
    years: "4+ years",
    jobId: "BLK-771",
    referrer: { name: "Karan Malhotra", role: "Principal Designer, Blinkit" },
    when: "Monday",
    skills: ["Interaction design", "Figma", "User research", "Prototyping", "Product strategy", "Design system", "Motion design"],
    missing: ["Design system", "Motion design"],
    work: ["On-site", "Joining within 30 days"],
    about: "Design the shopping app that delivers in 10 minutes. Make search, cart and checkout fast for millions of orders a day.",
    looking: ["4+ years of consumer product design", "Speed without losing craft", "Experience with e-commerce", "Strong interaction design"],
    resp: ["Own search and discovery", "Ship weekly with product and engineering", "Test ideas with real orders", "Mentor two designers"],
    tips: ["Show speed: how fast you went from idea to live", "Bring before and after numbers", "Keep it to three projects"],
    employer: "Blinkit, part of Eternal, is India’s largest quick-commerce app, delivering groceries in minutes.",
  },
  {
    id: "cred",
    title: "Visual Interaction Designer",
    company: "CRED",
    logo: "cred",
    banner: { bg: "#0F0F0F", src: "/images/sidedoor/cred.svg", w: 160, h: 52 },
    city: "Bengaluru, KA",
    cityShort: "Bengaluru",
    pay: "₹30–42 LPA",
    years: "3+ years",
    jobId: "CR-418",
    referrer: { name: "Tanvi Iyer", role: "Design Lead, CRED" },
    when: "Monday",
    skills: ["Interaction design", "Motion design", "Visual design", "Figma", "Prototyping", "Design system", "3D"],
    missing: ["Motion design", "Visual design", "Design system", "3D"],
    common: { logo: "makemytrip", text: "Both worked at MakeMyTrip" },
    work: ["On-site", "Joining within 45 days"],
    about: "Craft the moments CRED is known for: rewards, payments and the small animations members talk about.",
    looking: ["3+ years of visual and interaction design", "A portfolio with motion work", "An eye for detail", "Comfort with prototyping tools"],
    resp: ["Design and animate reward journeys", "Build motion specs with engineers", "Push the visual language forward", "Review work across the team"],
    tips: ["Motion matters here: show videos, not stills", "Explain why a detail was worth it", "Show personal projects too"],
    employer: "CRED rewards people for paying their credit card bills on time, with a design-led app used by millions.",
  },
  {
    id: "microsoft",
    title: "Product Designer II, Teams",
    company: "Microsoft",
    logo: "microsoft",
    banner: { bg: "#0067B8", src: "/images/sidedoor/microsoft.svg", w: 44, h: 44, keep: true, word: "Microsoft", wordColor: "#fff" },
    city: "Hyderabad, TS",
    cityShort: "Hyderabad",
    pay: "₹38–52 LPA",
    years: "4+ years",
    jobId: "MS-1776",
    referrer: { name: "Neha Kulkarni", role: "Principal Designer, Microsoft" },
    when: "14 Sep",
    skills: ["Interaction design", "Accessibility", "Figma", "User research", "Prototyping", "Fluent design", "Systems thinking"],
    missing: ["Accessibility", "Fluent design"],
    work: ["Hybrid", "Joining within 60 days"],
    about: "Design meetings and chat in Microsoft Teams for 300 million people, from Hyderabad’s India Development Center.",
    looking: ["4+ years designing complex products", "Accessibility-first thinking", "Strong systems thinking", "Clear communication"],
    resp: ["Own a part of the meetings experience", "Design with Fluent components", "Work with research on global studies", "Write design specs"],
    tips: ["Show a complex workflow you made simple", "Mention accessibility in your process", "Explain trade-offs you made"],
    employer: "Microsoft builds Windows, Office, Teams and Azure. Its India Development Center is in Hyderabad.",
  },
  {
    id: "zepto",
    title: "Product Designer-II",
    company: "Zepto",
    logo: "zepto",
    banner: { bg: "#950EDB", src: "/images/sidedoor/zepto.svg", w: 200, h: 69 },
    city: "Mumbai, MH",
    cityShort: "Mumbai",
    pay: "₹32–40 LPA",
    years: "3+ years",
    jobId: "ZP-512",
    referrer: { name: "Rahul Deshpande", role: "Senior Product Designer, Zepto" },
    when: "13 Sep",
    skills: ["Interaction design", "Figma", "Prototyping", "User research", "A/B testing", "Product strategy", "Design system"],
    missing: ["A/B testing"],
    work: ["On-site", "Joining within 30 days"],
    about: "Design the Zepto app for 10-minute deliveries: home, search and the cafe. Ship fast and test everything.",
    looking: ["3+ years of product design", "Experience with experiments", "Fast, clear decision making", "Strong craft in Figma"],
    resp: ["Own the home and search experience", "Run A/B tests with product", "Ship every week", "Work closely with brand"],
    tips: ["Show experiments and what you learned", "Talk about speed and quality", "Keep your portfolio short"],
    employer: "Zepto is a quick-commerce app that delivers groceries and more in about 10 minutes across Indian cities.",
  },
  {
    id: "zomato",
    title: "Member of Technical Staff-I",
    company: "Zomato",
    logo: "zomato",
    banner: { bg: "#E23744", src: "/images/sidedoor/zomato.svg", w: 230, h: 51 },
    city: "Noida, UP",
    cityShort: "Noida",
    pay: "₹25–30 LPA",
    years: "4+ years",
    jobId: "ZMT-203",
    referrer: { name: "Vanya Kapoor", role: "Product Designer, Zomato" },
    when: "12 Sep",
    skills: ["Interaction design", "Figma", "User research", "Prototyping", "Product strategy", "Design system", "Food-tech"],
    missing: ["Design system", "Food-tech"],
    work: ["On-site", "Joining within 30 days"],
    about: "Design ordering and dining out on Zomato. Make it easy to find a meal and trust it will arrive right.",
    looking: ["4+ years of product design", "Strong interaction design", "Comfort with data", "A love for food helps"],
    resp: ["Own ordering and restaurant pages", "Work with research on diner habits", "Ship with engineering every sprint", "Improve design quality across flows"],
    tips: ["Show one deep project over many shallow ones", "Explain your research", "Order from Zomato before the interview"],
    employer: "Zomato helps people discover restaurants and order food across 800+ Indian cities.",
  },
  {
    id: "groww",
    title: "Product Designer",
    company: "Groww",
    logo: "groww",
    banner: { bg: "#00D09C", src: "/images/sidedoor/groww.png", w: 190, h: 52 },
    city: "Bengaluru, KA",
    cityShort: "Bengaluru",
    pay: "₹26–34 LPA",
    years: "2+ years",
    jobId: "GRW-310",
    referrer: { name: "Meera Pillai", role: "Design Manager, Groww" },
    when: "11 Sep",
    skills: ["Interaction design", "Figma", "User research", "Fintech", "Prototyping", "Data visualisation", "Usability testing"],
    missing: ["Fintech", "Data visualisation"],
    common: { text: "Both studied at NID" },
    work: ["Hybrid", "Joining within 30 days"],
    about: "Make investing simple for first-time investors. Design stocks, mutual funds and the charts that explain them.",
    looking: ["2+ years of product design", "Clarity with numbers and charts", "Empathy for new investors", "Strong craft"],
    resp: ["Design investing flows", "Make charts easy to read", "Test with first-time investors", "Work with compliance on clear copy"],
    tips: ["Show how you explained something complex", "Charts or dashboards are a plus", "Keep your copy plain"],
    employer: "Groww is one of India’s largest investing apps, with over 10 million active investors.",
  },
  {
    id: "razorpay",
    title: "Senior Product Designer",
    company: "Razorpay",
    logo: "razorpay",
    banner: { bg: "#072654", src: "/images/sidedoor/razorpay.svg", w: 220, h: 46 },
    city: "Bengaluru, KA",
    cityShort: "Bengaluru",
    pay: "₹35–48 LPA",
    years: "5+ years",
    jobId: "RZP-240",
    referrer: { name: "Pooja Sharma", role: "Design Manager, Razorpay" },
    when: "10 Sep",
    skills: ["Interaction design", "Design system", "B2B SaaS", "Figma", "User research", "Prototyping", "Systems thinking"],
    missing: ["Design system", "B2B SaaS"],
    work: ["Hybrid", "Joining within 45 days"],
    about: "Design the dashboard businesses use to take payments, pay vendors and run payroll.",
    looking: ["5+ years of product design", "B2B or SaaS experience", "Systems thinking", "Mentoring experience"],
    resp: ["Own the payments dashboard", "Grow the Blade design system", "Research with finance teams", "Lead design reviews"],
    tips: ["Show complex B2B work", "Explain how you worked with engineers", "Talk about design systems"],
    employer: "Razorpay powers online payments for millions of Indian businesses.",
  },
];

export const jobById = (id: string) => JOBS.find((j) => j.id === id) ?? JOBS[0];
export const matchOf = (j: Job) => j.skills.length - j.missing.length;
export const firstName = (n: string) => n.split(" ")[0];

/* ── the candidate's own profile (Abhinav) ────────────────────────────────── */
export type Exp = { logo: string; role: string; company: string; when: string };
export type Proj = { title: string; skills: string[]; detail: string };

export const ABHINAV_PROFILE = {
  name: "Abhinav Saxena",
  email: "abhinav.saxena@email.com",
  phone: "+91 98765 43221",
  city: "Bengaluru, KA",
  experience: "3 yrs total · 3 yrs relevant",
  skills: "Product strategy, Systems thinking, User research, Interaction design, Figma",
  jobs: [
    { logo: "blinkit", role: "Product Designer", company: "Blinkit", when: "Sep 2023–Present" },
    { logo: "makemytrip", role: "Associate Product Designer", company: "MakeMyTrip", when: "Jun 2022–Aug 2023" },
  ] as Exp[],
  projects: [
    {
      title: "Blinkit Merchant App UX Revamp",
      skills: ["Product strategy", "Systems design", "Prototyping", "User research", "Figma"],
      detail: "Rebuilt order intake for 4,000 dark-store merchants. Cut the time to accept an order from 40s to 12s.",
    },
    {
      title: "MakeMyTrip Booking Experience Redesign",
      skills: ["User research", "Interaction design", "Usability testing", "Figma"],
      detail: "Redesigned hotel checkout from five steps to three. Drop-off at payment fell 18% in the A/B test.",
    },
  ] as Proj[],
  linkedin: "",
  portfolio: "",
};
export type Profile = typeof ABHINAV_PROFILE;

/** What a blank field fills itself with on a tap, so testers never have to type. */
export const DEMO = {
  linkedin: "linkedin.com/in/abhinav-saxena",
  portfolio: "dribbble.com/abhinavsaxena",
  note: "I led the merchant app redesign at Blinkit. Happy to share more.",
  gaps: "0",
  locations: "Bengaluru, Remote",
  notice: "30",
  code: "593 217",
  jobId: "184223",
  tips: "Link a portfolio with two end-to-end case studies. Show the problem, your choice and the result.",
  support: "My request to Flipkart still says Sent after a week.",
  newProject: { title: "Swiggy Instamart Search Redesign", skills: ["Interaction design", "A/B testing"], detail: "Made search results load in under a second and cut empty searches by 30%." },
  newJob: { logo: "swiggy", role: "Design Intern", company: "Swiggy", when: "Jan 2022–May 2022" },
  skillIdeas: ["AI-assisted design", "Design system", "A/B testing", "Motion design", "Accessibility"],
};

/* ── candidates who asked Nithin (the referrer's side) ─────────────────────── */
/** The seven skills Nithin's Interaction Designer post asks for. */
export const POST_SKILLS = ["Interaction design", "Figma", "User research", "Prototyping", "AI-assisted design", "Design system", "A/B testing"];

export type Candidate = {
  id: string;
  name: string;
  title: string;
  company: string;
  logo?: string;
  years: number;
  /** which of the post's skills their resume shows, and where it came from */
  has: Record<string, string>;
  when: string;
  common?: { logo?: string; icon?: "building.2.fill"; text: string; years?: string };
  city: string;
  notice: string;
  work: string[];
  jobs: Exp[];
  projects: Proj[];
  note: string;
  email: string;
  phone: string;
  dob: string;
  gaps: string;
  locations: string;
  /** V6 draws one lower-match request whose resume says too little to judge fit */
  thin?: boolean;
};

const from = (co: string) => `From resume · ${co}`;

export const CANDIDATES: Candidate[] = [
  {
    id: "abhinav",
    name: "Abhinav Saxena",
    title: "Product Designer",
    company: "Blinkit",
    logo: "blinkit",
    years: 3,
    has: { "Interaction design": from("MakeMyTrip"), Figma: from("Blinkit"), "User research": from("Blinkit"), Prototyping: from("Blinkit") },
    when: "Today",
    common: { logo: "makemytrip", text: "Both worked at MakeMyTrip", years: "You 2021–22 · Abhinav 2022–23" },
    city: "Bengaluru, KA",
    notice: "30 days",
    work: ["Full time", "Remote or hybrid"],
    jobs: ABHINAV_PROFILE.jobs,
    projects: ABHINAV_PROFILE.projects,
    note: "I led the merchant app redesign at Blinkit. Happy to share more.",
    email: "abhinav.saxena@email.com",
    phone: "+91 98XXX XXX21",
    dob: "12 Mar 1999",
    gaps: "0",
    locations: "Bengaluru, Remote",
  },
  {
    id: "kavya",
    name: "Kavya Reddy",
    title: "Product Designer",
    company: "Swiggy",
    logo: "swiggy",
    years: 4,
    has: { "Interaction design": from("Swiggy"), Figma: from("Swiggy"), "User research": from("Swiggy"), Prototyping: from("Swiggy"), "A/B testing": from("Swiggy") },
    when: "Today",
    common: { icon: "building.2.fill", text: "Both studied at NID", years: "You 2014–18 · Kavya 2016–20" },
    city: "Bengaluru, KA",
    notice: "60 days",
    work: ["Full time", "Hybrid"],
    jobs: [
      { logo: "swiggy", role: "Product Designer", company: "Swiggy", when: "Mar 2022–Present" },
      { logo: "razorpay", role: "UX Designer", company: "Razorpay", when: "Jul 2020–Feb 2022" },
    ],
    projects: [
      { title: "Swiggy Instamart Checkout", skills: ["Interaction design", "A/B testing", "Figma"], detail: "Cut checkout from four steps to two. Orders completed rose 9%." },
      { title: "Razorpay Payment Links", skills: ["User research", "Prototyping"], detail: "Redesigned links for small sellers. Support tickets fell by a third." },
    ],
    note: "I’ve shipped checkout at Swiggy for 2 years. Would love to do it at Flipkart’s scale.",
    email: "kavya.reddy@email.com",
    phone: "+91 99XXX XXX07",
    dob: "3 Feb 1998",
    gaps: "0",
    locations: "Bengaluru",
  },
  {
    id: "rohan",
    name: "Rohan Iyer",
    title: "Interaction Designer",
    company: "PhonePe",
    logo: "phonepe",
    years: 3,
    has: { "Interaction design": from("PhonePe"), Figma: from("PhonePe"), Prototyping: from("PhonePe"), "Design system": from("PhonePe") },
    when: "Today",
    city: "Pune, MH",
    notice: "30 days",
    work: ["Full time", "Remote or hybrid"],
    jobs: [
      { logo: "phonepe", role: "Interaction Designer", company: "PhonePe", when: "Aug 2022–Present" },
      { logo: "zomato", role: "Design Intern", company: "Zomato", when: "Jan 2022–Jul 2022" },
    ],
    projects: [
      { title: "PhonePe Bill Payments", skills: ["Interaction design", "Design system"], detail: "Built one bill-pay flow for 40 billers. Failed payments fell 12%." },
      { title: "Zomato Table Booking", skills: ["Prototyping", "Figma"], detail: "Prototyped booking for dine-out. Shipped to 5 cities." },
    ],
    note: "Payments are my thing. Checkout at Flipkart is the next step.",
    email: "rohan.iyer@email.com",
    phone: "+91 98XXX XXX44",
    dob: "21 Aug 1999",
    gaps: "0",
    locations: "Pune, Bengaluru",
  },
  {
    id: "arpita",
    name: "Arpita Singh",
    title: "Product Designer",
    company: "Myntra",
    years: 3,
    has: { "Interaction design": from("Myntra"), Figma: from("Myntra"), "User research": from("Myntra"), "Design system": from("Myntra") },
    when: "Yesterday",
    common: { icon: "building.2.fill", text: "Both studied at NID", years: "You 2014–18 · Arpita 2017–21" },
    city: "Bengaluru, KA",
    notice: "60 days",
    work: ["Full time", "Hybrid"],
    jobs: [{ role: "Product Designer", company: "Myntra", when: "Jul 2021–Present", logo: "" }],
    projects: [
      { title: "Myntra Try & Buy", skills: ["User research", "Interaction design"], detail: "Designed try-at-home for fashion. Returns fell 14%." },
      { title: "Myntra Design System", skills: ["Design system", "Figma"], detail: "Built 60 components used by 25 designers." },
    ],
    note: "Myntra checkout taught me a lot about fashion buyers. Happy to share.",
    email: "arpita.singh@email.com",
    phone: "+91 97XXX XXX48",
    dob: "4 Jul 1998",
    gaps: "0",
    locations: "Bengaluru, Remote",
  },
  {
    id: "sneha",
    name: "Sneha Kapoor",
    title: "Senior UX Designer",
    company: "Zomato",
    logo: "zomato",
    years: 5,
    has: {
      "Interaction design": from("Zomato"),
      Figma: from("Zomato"),
      "User research": from("Zomato"),
      Prototyping: from("Zomato"),
      "AI-assisted design": from("Zomato"),
      "A/B testing": from("Zomato"),
    },
    when: "Yesterday",
    city: "Gurugram, HR",
    notice: "90 days",
    work: ["Full time", "Remote"],
    jobs: [
      { logo: "zomato", role: "Senior UX Designer", company: "Zomato", when: "Apr 2021–Present" },
      { logo: "makemytrip", role: "UX Designer", company: "MakeMyTrip", when: "Jun 2019–Mar 2021" },
    ],
    projects: [
      { title: "Zomato AI Menu Search", skills: ["AI-assisted design", "Interaction design"], detail: "Search by craving, not dish name. Used in 1 in 5 searches." },
      { title: "Zomato Gold Checkout", skills: ["A/B testing", "Figma"], detail: "Ran 11 tests on the Gold upsell. Sign-ups up 22%." },
    ],
    note: "Five years in food delivery. Keen to move to commerce checkout.",
    email: "sneha.kapoor@email.com",
    phone: "+91 98XXX XXX63",
    dob: "17 Nov 1996",
    gaps: "0",
    locations: "Gurugram, Remote",
  },
  {
    id: "aditya",
    name: "Aditya Joshi",
    title: "Product Designer",
    company: "CRED",
    logo: "cred",
    years: 3,
    has: { "Interaction design": from("CRED"), Figma: from("CRED"), Prototyping: from("CRED"), "Design system": from("CRED") },
    when: "Yesterday",
    city: "Bengaluru, KA",
    notice: "45 days",
    work: ["Full time", "On-site"],
    jobs: [{ logo: "cred", role: "Product Designer", company: "CRED", when: "Jan 2022–Present" }],
    projects: [
      { title: "CRED Pay at Stores", skills: ["Interaction design", "Prototyping"], detail: "Tap-to-pay for offline stores. Live in 3,000 shops." },
      { title: "NeoPOP Components", skills: ["Design system", "Figma"], detail: "Added 18 components to CRED’s open design system." },
    ],
    note: "I care about details in payments. Here’s my Dribbble too.",
    email: "aditya.joshi@email.com",
    phone: "+91 90XXX XXX12",
    dob: "9 Jan 1999",
    gaps: "0",
    locations: "Bengaluru",
  },
  {
    id: "aviral",
    name: "Aviral Dixit",
    title: "UX Designer",
    company: "Razorpay",
    logo: "razorpay",
    years: 4,
    has: { "Interaction design": from("Razorpay"), "User research": from("Razorpay"), Figma: from("Razorpay") },
    when: "Tuesday",
    city: "Bengaluru, KA",
    notice: "30 days",
    work: ["Full time", "Hybrid"],
    jobs: [
      { logo: "razorpay", role: "UX Designer", company: "Razorpay", when: "May 2021–Present" },
      { logo: "groww", role: "Associate UX Designer", company: "Groww", when: "Jun 2020–Apr 2021" },
    ],
    projects: [
      { title: "Razorpay Checkout Revamp", skills: ["Interaction design", "User research"], detail: "One checkout for cards, UPI and EMI. Success rate up 4 points." },
      { title: "Groww SIP Setup", skills: ["Figma"], detail: "Made starting an SIP a 3-tap flow." },
    ],
    note: "I’ve spent four years on checkout. Happy to walk you through it.",
    email: "aviral.dixit@email.com",
    phone: "+91 98XXX XXX90",
    dob: "28 May 1997",
    gaps: "0",
    locations: "Bengaluru",
  },
  {
    id: "priya",
    name: "Priya Nair",
    title: "Senior Product Designer",
    company: "Zepto",
    logo: "zepto",
    years: 6,
    has: {
      "Interaction design": from("Zepto"),
      Figma: from("Zepto"),
      "User research": from("Amazon"),
      Prototyping: from("Zepto"),
      "Design system": from("Zepto"),
    },
    when: "Monday",
    city: "Mumbai, MH",
    notice: "60 days",
    work: ["Full time", "Remote or hybrid"],
    jobs: [
      { logo: "zepto", role: "Senior Product Designer", company: "Zepto", when: "Feb 2023–Present" },
      { logo: "amazon", role: "UX Designer", company: "Amazon", when: "Jul 2019–Jan 2023" },
    ],
    projects: [
      { title: "Zepto Cafe Ordering", skills: ["Interaction design", "Prototyping"], detail: "Launched hot food inside the grocery app in 8 weeks." },
      { title: "Amazon Pay Later", skills: ["User research", "Design system"], detail: "Designed credit onboarding for first-time borrowers." },
    ],
    note: "I’d move to Bengaluru for this role.",
    email: "priya.nair@email.com",
    phone: "+91 99XXX XXX31",
    dob: "12 Dec 1995",
    gaps: "0",
    locations: "Mumbai, Bengaluru",
  },
  {
    id: "varun",
    name: "Varun Bhatia",
    title: "UX Designer",
    company: "Google",
    logo: "google",
    years: 3,
    has: { "Interaction design": from("Google"), "User research": from("Google"), Prototyping: from("Google") },
    when: "Monday",
    city: "Hyderabad, TS",
    notice: "60 days",
    work: ["Full time", "Hybrid"],
    jobs: [{ logo: "google", role: "UX Designer", company: "Google", when: "Aug 2022–Present" }],
    projects: [
      { title: "Google Pay Bill Reminders", skills: ["Interaction design", "User research"], detail: "Reminders that users trust. Late payments fell 17%." },
      { title: "Maps Offline Areas", skills: ["Prototyping"], detail: "Prototyped offline downloads for low-storage phones." },
    ],
    note: "Looking for a faster team. Checkout would be great.",
    email: "varun.bhatia@email.com",
    phone: "+91 97XXX XXX85",
    dob: "5 Oct 1998",
    gaps: "0",
    locations: "Hyderabad, Bengaluru",
  },
  {
    id: "tanya",
    name: "Tanya Mehta",
    title: "Product Designer",
    company: "Meta",
    logo: "meta",
    years: 4,
    has: { "Interaction design": from("Meta"), Figma: from("Meta"), Prototyping: from("Meta"), "A/B testing": from("Meta") },
    when: "14 Sep",
    city: "Gurugram, HR",
    notice: "90 days",
    work: ["Full time", "Remote"],
    jobs: [
      { logo: "meta", role: "Product Designer", company: "Meta", when: "Oct 2021–Present" },
      { logo: "phonepe", role: "Visual Designer", company: "PhonePe", when: "Jun 2020–Sep 2021" },
    ],
    projects: [
      { title: "WhatsApp Catalogue", skills: ["Interaction design", "A/B testing"], detail: "Let shops share catalogues in chat. Used by 2M businesses." },
      { title: "PhonePe Rewards", skills: ["Figma", "Prototyping"], detail: "Redesigned scratch cards and rewards." },
    ],
    note: "Would love to talk about commerce in chat.",
    email: "tanya.mehta@email.com",
    phone: "+91 98XXX XXX19",
    dob: "30 Mar 1997",
    gaps: "0",
    locations: "Gurugram, Remote",
  },
  {
    id: "amit",
    name: "Amit Patel",
    title: "Visual Designer",
    company: "Freelance",
    years: 2,
    has: {},
    when: "2 days ago",
    thin: true,
    city: "Pune, MH",
    notice: "60 days",
    work: ["Full time", "Remote"],
    jobs: [{ logo: "", role: "Visual Designer", company: "Freelance", when: "2023–Present" }],
    projects: [],
    note: "",
    email: "amit.patel@email.com",
    phone: "+91 98XXX XXX70",
    dob: "14 Apr 2000",
    gaps: "0",
    locations: "Pune",
  },
  {
    id: "nisha",
    name: "Nisha Rao",
    title: "UI Designer",
    company: "Urban Company",
    years: 2,
    has: { Figma: from("Urban Company"), "Interaction design": from("Urban Company") },
    when: "12 Sep",
    city: "Bengaluru, KA",
    notice: "30 days",
    work: ["Full time", "Hybrid"],
    jobs: [{ logo: "", role: "UI Designer", company: "Urban Company", when: "Jul 2023–Present" }],
    projects: [{ title: "Urban Company Booking", skills: ["Figma"], detail: "Redesigned slot booking for home services." }],
    note: "Early in my career but I learn fast.",
    email: "nisha.rao@email.com",
    phone: "+91 96XXX XXX52",
    dob: "22 Jun 2001",
    gaps: "0",
    locations: "Bengaluru",
  },
  {
    id: "ishaan",
    name: "Ishaan Malhotra",
    title: "Product Designer",
    company: "Groww",
    logo: "groww",
    years: 2,
    has: { "Interaction design": from("Groww"), Figma: from("Groww"), "User research": from("Groww") },
    when: "11 Sep",
    city: "Bengaluru, KA",
    notice: "30 days",
    work: ["Full time", "Remote or hybrid"],
    jobs: [{ logo: "groww", role: "Product Designer", company: "Groww", when: "Jun 2023–Present" }],
    projects: [{ title: "Groww Stock Alerts", skills: ["Interaction design", "User research"], detail: "Price alerts that don’t spam. Opt-outs fell by half." }],
    note: "I’ve applied twice on the portal with no reply. A referral would help.",
    email: "ishaan.malhotra@email.com",
    phone: "+91 98XXX XXX26",
    dob: "8 Sep 2000",
    gaps: "0",
    locations: "Bengaluru",
  },
  {
    id: "diya",
    name: "Diya Sharma",
    title: "UX Designer",
    company: "Microsoft",
    logo: "microsoft",
    years: 1,
    has: { Figma: from("Microsoft"), Prototyping: from("Microsoft") },
    when: "10 Sep",
    city: "Hyderabad, TS",
    notice: "60 days",
    work: ["Full time", "Hybrid"],
    jobs: [{ logo: "microsoft", role: "UX Designer", company: "Microsoft", when: "Jul 2024–Present" }],
    projects: [{ title: "Teams Meeting Recap", skills: ["Figma", "Prototyping"], detail: "Designed AI recap cards for missed meetings." }],
    note: "First job after IIT Bombay IDC. Keen to grow in consumer products.",
    email: "diya.sharma@email.com",
    phone: "+91 91XXX XXX38",
    dob: "19 Jan 2002",
    gaps: "0",
    locations: "Hyderabad, Bengaluru",
  },
];

export const SUGGESTED: Candidate[] = [
  {
    ...CANDIDATES[4],
    id: "shreya",
    name: "Shreya Verma",
    title: "UX Designer",
    company: "CRED",
    logo: "cred",
    years: 4,
    when: "",
    common: { icon: "building.2.fill", text: "Both studied at NID" },
    has: {
      "Interaction design": from("CRED"),
      Figma: from("CRED"),
      "User research": from("CRED"),
      Prototyping: from("CRED"),
      "Design system": from("CRED"),
    },
  },
  { ...CANDIDATES[1], id: "advika", name: "Advika Singh", title: "Product Designer", company: "Meesho", logo: undefined, years: 3, when: "", common: undefined },
  { ...CANDIDATES[2], id: "manav", name: "Manav Gupta", title: "Interaction Designer", company: "Amazon", logo: "amazon", years: 5, when: "", common: undefined },
];

export const candidateById = (id: string) => [...CANDIDATES, ...SUGGESTED].find((c) => c.id === id) ?? CANDIDATES[0];
export const roleLine = (c: Candidate) => (c.company === "Freelance" ? c.title : `${c.title}, ${c.company}`);
export const matchLine = (c: Candidate) => (c.thin ? "Not enough to judge" : `${Object.keys(c.has).length} of 7 skills · ${c.years} ${c.years === 1 ? "yr" : "yrs"}`);
